"""
models.py
=========

Pydantic models for the ingestion API. Pydantic is doing the
"validate/parse payloads" requirement for us: any field with the wrong
type, or a missing required field, is rejected with a 422 automatically.

This is the trust boundary. The SDK is one client today, but the
ingestion endpoint must assume payloads could be malformed or hostile,
so every field is typed and constrained here.
"""
from __future__ import annotations
import datetime as dt
from typing import Literal, Optional
from pydantic import BaseModel, Field


class InferenceLogIn(BaseModel):
    """Shape of the JSON the SDK POSTs to /ingest."""

    log_id: str = Field(..., description="UUID generated by the SDK")
    conversation_id: Optional[str] = Field(
        None, description="Session this call belongs to; may be null"
    )

    provider: str = Field(..., min_length=1, max_length=64)
    model: str = Field(..., min_length=1, max_length=128)

    latency_ms: Optional[int] = Field(None, ge=0)
    prompt_tokens: Optional[int] = Field(None, ge=0)
    completion_tokens: Optional[int] = Field(None, ge=0)
    total_tokens: Optional[int] = Field(None, ge=0)

    # Literal restricts status to exactly these two strings.
    status: Literal["success", "error"]
    error_message: Optional[str] = None

    input_preview: Optional[str] = Field(None, max_length=2000)
    output_preview: Optional[str] = Field(None, max_length=2000)

    request_started_at: Optional[dt.datetime] = None


class IngestResponse(BaseModel):
    """What /ingest returns to the SDK."""
    accepted: bool
    log_id: str
